### ISSUE TITLE
Error on SendMessage if missing permissions

### ISSUE THREAD

**Issue by CoasterFreakDE** [DevSkyOne/OpenGPT#9]
```sh
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 451, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/opengpt.py", line 313, in on_message
    thinking_message = await send_thinking_message(message)
  File "/home/container/opengpt.py", line 252, in send_thinking_message
    return await message.channel.send("Let me think for a moment... (this may take a while)", reference=message)
  File "/home/container/.local/lib/python3.10/site-packages/discord/abc.py", line 1140, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/home/container/.local/lib/python3.10/site-packages/discord/http.py", line 590, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

**Comment by ozgurakinj** [comment]
what is the expected behaviour? catch the exception and print an error?

**Comment by mccoderpy** [comment]
Well check it before responding would also be an option

**Comment by CoasterFreakDE** [comment]
Good question. If the bot has no permission to send a message, there is no way of letting them know. (Only option is to use slashcommands for new conversations)
